// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class BottleTrap_GGPS_Constants
{
        public const string achievement_unlimited_level_20 = "CgkInuvqpcAGEAIQAg"; // <GPGSID>
        public const string achievement_campaign_level_20 = "CgkInuvqpcAGEAIQEA"; // <GPGSID>
        public const string achievement_unlimited_level_500 = "CgkInuvqpcAGEAIQBg"; // <GPGSID>
        public const string achievement_unlimited_level_10 = "CgkInuvqpcAGEAIQAQ"; // <GPGSID>
        public const string achievement_campaign_level_100 = "CgkInuvqpcAGEAIQEg"; // <GPGSID>
        public const string achievement_campaign_level_10 = "CgkInuvqpcAGEAIQCg"; // <GPGSID>
        public const string achievement_unlimited_level_100 = "CgkInuvqpcAGEAIQBA"; // <GPGSID>
        public const string achievement_level_less_than_2s = "CgkInuvqpcAGEAIQDQ"; // <GPGSID>
        public const string leaderboard_best_unlimited_level = "CgkInuvqpcAGEAIQDA"; // <GPGSID>
        public const string achievement_unlimited_level_1000 = "CgkInuvqpcAGEAIQBw"; // <GPGSID>
        public const string achievement_campaign_level_5 = "CgkInuvqpcAGEAIQCQ"; // <GPGSID>
        public const string achievement_unlimited_level_50 = "CgkInuvqpcAGEAIQAw"; // <GPGSID>
        public const string achievement_campaign_level_50 = "CgkInuvqpcAGEAIQEQ"; // <GPGSID>
        public const string achievement_level_less_than_10s = "CgkInuvqpcAGEAIQDw"; // <GPGSID>
        public const string leaderboard_unlimited_high_scores = "CgkInuvqpcAGEAIQCw"; // <GPGSID>
        public const string leaderboard_campaign_highscores = "CgkInuvqpcAGEAIQCA"; // <GPGSID>
        public const string achievement_level_less_than_5s = "CgkInuvqpcAGEAIQDg"; // <GPGSID>
        public const string achievement_unlimited_level_200 = "CgkInuvqpcAGEAIQBQ"; // <GPGSID>
        public const string achievement_level_less_than_1s = "CgkInuvqpcAGEAIQEw"; // <GPGSID>

}

